Repository WordPress/openverse-catalog, pull requests merged in 2021-09, with the labels that each got.

#173 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#174 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#180 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#179 Add recreate recipe
  README.md
  justfile
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#184 Renamed the source suggestion issue template
  .github/ISSUE_TEMPLATE/new-source-suggestion.md
Labels: 🛠 goal: fix, 📄 aspect: text

#185 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#187 Streamline dag lists in README.md and add StockSnap
  README.md
Labels: 📄 aspect: text, 🧰 goal: internal improvement

#195 Issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/code_quality.md
  .github/ISSUE_TEMPLATE/general-feature-request.md
  .github/ISSUE_TEMPLATE/image_provider_api_integration_request.md
  .github/ISSUE_TEMPLATE/infrastructure_improvement.md
  .github/ISSUE_TEMPLATE/new_source_suggestion.md
Labels: 🛠 goal: fix, 🤖 aspect: dx

#194 Update README.md with Airflow Credentials
  README.md
Labels: ✨ goal: improvement, 📄 aspect: text

#192 Move storage module up and deduplicate MediaStore tests
  openverse_catalog/dags/common/storage/test_image.py
  openverse_catalog/dags/provider_api_scripts/brooklyn_museum.py
  openverse_catalog/dags/provider_api_scripts/cleveland_museum_of_art.py
  openverse_catalog/dags/provider_api_scripts/europeana.py
  openverse_catalog/dags/provider_api_scripts/finnish_museums.py
  openverse_catalog/dags/provider_api_scripts/flickr.py
  openverse_catalog/dags/provider_api_scripts/jamendo.py
  openverse_catalog/dags/provider_api_scripts/metropolitan_museum_of_art.py
  openverse_catalog/dags/provider_api_scripts/museum_victoria.py
  openverse_catalog/dags/provider_api_scripts/nypl.py
  openverse_catalog/dags/provider_api_scripts/phylopic.py
  openverse_catalog/dags/provider_api_scripts/raw_pixel.py
  openverse_catalog/dags/provider_api_scripts/science_museum.py
  openverse_catalog/dags/provider_api_scripts/smithsonian.py
  openverse_catalog/dags/provider_api_scripts/staten_museum.py
  openverse_catalog/dags/provider_api_scripts/stocksnap.py
  openverse_catalog/dags/provider_api_scripts/test_cleveland_museum_of_art.py
  openverse_catalog/dags/provider_api_scripts/test_raw_pixel.py
  openverse_catalog/dags/provider_api_scripts/test_science_museum.py
  openverse_catalog/dags/provider_api_scripts/walters_art_museum.py
  openverse_catalog/dags/provider_api_scripts/wikimedia_commons.py
  openverse_catalog/dags/storage/__init__.py
  openverse_catalog/dags/storage/audio.py
  openverse_catalog/dags/storage/column_names.py
  openverse_catalog/dags/storage/columns.py
  openverse_catalog/dags/storage/image.py
  openverse_catalog/dags/storage/media.py
  openverse_catalog/dags/storage/test_audio.py
  openverse_catalog/dags/storage/test_columns.py
  openverse_catalog/dags/storage/test_image.py
  openverse_catalog/dags/storage/test_media.py
  openverse_catalog/dags/storage/test_util.py
  openverse_catalog/dags/storage/util.py
  openverse_catalog/dags/util/constants.py
  openverse_catalog/dags/util/loader/ingestion_column.py
  openverse_catalog/dags/util/loader/sql.py
  openverse_catalog/dags/util/pg_cleaner.py
  openverse_catalog/dags/util/popularity/sql.py
  openverse_catalog/dags/util/tsv_cleaner.py
Labels: 💻 aspect: code, 🧰 goal: internal improvement
