Repository WordPress/openverse-catalog, pull requests merged in 2021-11, with the labels that each got.

#280 Add index creation for matviews
  docker/local_postgres/0004_openledger_image_view.sql
  docker/local_postgres/0007_openledger_audio_view.sql
Labels: 🛠 goal: fix, 💻 aspect: code

#286 Remove tsv_to_postgres_loader_overwrite
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/operators.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/database/loader_workflow.py
  tests/dags/common/loader/test_sql.py
  tests/dags/test_dag_parsing.py
Labels: ✨ goal: improvement, 💻 aspect: code

#288 Retire cleaner_worfklow, pg_cleaner
  openverse_catalog/dags/retired/cleaner_workflow.py
  openverse_catalog/dags/retired/common/pg_cleaner.py
  tests/dags/common/test_pg_cleaner.py
  tests/dags/test_dag_parsing.py
Labels: ✨ goal: improvement, 💻 aspect: code

#287 Retire legacy ingestion column fix
  openverse_catalog/dags/common/loader/paths.py
  openverse_catalog/dags/retired/common/ingestion_column.py
  tests/dags/common/loader/test_ingestion_column.py
Labels: ✨ goal: improvement, 💻 aspect: code

#271 Add production deployment documentation
  DEPLOY.md
  README.md
  deploy_in_prod.sh
  docker-compose.override.yml
  docker/airflow/Dockerfile
  env.template
Labels: 🌟 goal: addition, 📄 aspect: text

#277 Add DAG tags, remove health check workflow
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/commoncrawl/sync_commoncrawl_workflow.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/database/loader_workflow.py
  openverse_catalog/dags/database/recreate_audio_popularity_calculation.py
  openverse_catalog/dags/database/recreate_image_popularity_calculation.py
  openverse_catalog/dags/database/refresh_all_audio_popularity_data.py
  openverse_catalog/dags/database/refresh_all_image_popularity_data.py
  openverse_catalog/dags/database/refresh_audio_view_data.py
  openverse_catalog/dags/database/refresh_image_view_data.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/oauth2/authorize_dag.py
  openverse_catalog/dags/oauth2/token_refresh_dag.py
  openverse_catalog/dags/providers/check_new_smithsonian_unit_codes_workflow.py
  openverse_catalog/dags/providers/healthcheck_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/healthcheck.py
  openverse_catalog/dags/retired/cleaner_workflow.py
Labels: 🌟 goal: addition, 💻 aspect: code

#279 Slack alerting utilities
  docker/airflow/Dockerfile
  docker/airflow/entrypoint.sh
  env.template
  justfile
  openverse_catalog/dags/common/slack.py
  requirements_prod.txt
  tests/dags/common/test_slack.py
Labels: 🌟 goal: addition, 💻 aspect: code

#289 Reduce TSV loader complexity
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/operators.py
  openverse_catalog/dags/common/loader/paths.py
  openverse_catalog/dags/database/loader_workflow.py
  tests/dags/common/loader/test_paths.py
Labels: ✨ goal: improvement, 💻 aspect: code

#95 Add Provider API script for Freesound
  env.template
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/common/popularity/sql.py
  openverse_catalog/dags/providers/freesound_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  tests/dags/providers/provider_api_scripts/resources/freesound/audio_data_example.json
  tests/dags/providers/provider_api_scripts/resources/freesound/page.json
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code, ☁️ provider: audio

#293 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx
