Repository WordPress/openverse-catalog, pull requests merged in 2021-12, with the labels that each got.

#294 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_ping.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#296 Retire common_api_workflows, clean up config
  openverse_catalog/dags/common/config.py
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/retired/common_api_workflows.py
  tests/dags/test_common_api_workflows.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#295 Specific error message for auth errors on request, improve tests
  openverse_catalog/dags/common/requester.py
  tests/dags/common/test_requester.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#297 Slack alerting for DAG failures
  DEPLOY.md
  env.template
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/database/loader_workflow.py
  openverse_catalog/dags/database/recreate_audio_popularity_calculation.py
  openverse_catalog/dags/database/recreate_image_popularity_calculation.py
  openverse_catalog/dags/database/refresh_all_audio_popularity_data.py
  openverse_catalog/dags/database/refresh_all_image_popularity_data.py
  openverse_catalog/dags/database/refresh_audio_view_data.py
  openverse_catalog/dags/database/refresh_image_view_data.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/oauth2/authorize_dag.py
  openverse_catalog/dags/oauth2/token_refresh_dag.py
  tests/dags/common/test_slack.py
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#299 Remove unnecessary logging.basicConfig calls
  openverse_catalog/dags/common/etl/scripts/ExtractCCLinks.py
  openverse_catalog/dags/common/log_cleanup.py
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/commoncrawl/commoncrawl_scripts/commoncrawl_s3_syncer/SyncImageProviders.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/database/recreate_audio_popularity_calculation.py
  openverse_catalog/dags/database/recreate_image_popularity_calculation.py
  openverse_catalog/dags/database/refresh_all_audio_popularity_data.py
  openverse_catalog/dags/database/refresh_all_image_popularity_data.py
  openverse_catalog/dags/database/refresh_audio_view_data.py
  openverse_catalog/dags/database/refresh_image_view_data.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/providers/brooklyn_museum_workflow.py
  openverse_catalog/dags/providers/check_new_smithsonian_unit_codes_workflow.py
  openverse_catalog/dags/providers/cleveland_museum_workflow.py
  openverse_catalog/dags/providers/europeana_ingestion_workflow.py
  openverse_catalog/dags/providers/europeana_workflow.py
  openverse_catalog/dags/providers/finnish_museums_workflow.py
  openverse_catalog/dags/providers/flickr_ingestion_workflow.py
  openverse_catalog/dags/providers/flickr_workflow.py
  openverse_catalog/dags/providers/freesound_workflow.py
  openverse_catalog/dags/providers/jamendo_workflow.py
  openverse_catalog/dags/providers/metropolitan_museum_workflow.py
  openverse_catalog/dags/providers/museum_victoria_workflow.py
  openverse_catalog/dags/providers/nypl_workflow.py
  openverse_catalog/dags/providers/phylopic_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/Thingiverse.py
  tests/dags/providers/provider_api_scripts/test_flickr.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#301 Remove `get_*_operator` functions, simplify commoncrawl logic
  openverse_catalog/dags/.airflowignore
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/etl/operators.py
  openverse_catalog/dags/common/loader/operators.py
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/commoncrawl/commoncrawl_utils.py
  openverse_catalog/dags/commoncrawl/sync_commoncrawl_workflow.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/providers/check_new_smithsonian_unit_codes_workflow.py
  tests/dags/common/etl/test_commoncrawl_utils.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#302 Add Image Categories
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
  tests/dags/providers/provider_api_scripts/resources/flickr/image_data_complete_example.json
  tests/dags/providers/provider_api_scripts/test_flickr.py
  tests/dags/providers/provider_api_scripts/test_stocksnap.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#306 Add unique indices to catalog
  docker/local_postgres/0003_openledger_image_schema.sql
  docker/local_postgres/0006_openledger_audio_schema.sql
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#308 Upgrade to Airflow 2.2.3
  docker/airflow/Dockerfile
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/database/loader_workflow.py
  openverse_catalog/dags/database/recreate_audio_popularity_calculation.py
  openverse_catalog/dags/database/recreate_image_popularity_calculation.py
  openverse_catalog/dags/database/refresh_all_audio_popularity_data.py
  openverse_catalog/dags/database/refresh_all_image_popularity_data.py
  openverse_catalog/dags/database/refresh_audio_view_data.py
  openverse_catalog/dags/database/refresh_image_view_data.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/providers/check_new_smithsonian_unit_codes_workflow.py
  openverse_catalog/dags/providers/cleveland_museum_workflow.py
  openverse_catalog/dags/providers/europeana_ingestion_workflow.py
  openverse_catalog/dags/providers/europeana_workflow.py
  openverse_catalog/dags/providers/flickr_ingestion_workflow.py
  openverse_catalog/dags/providers/flickr_workflow.py
  openverse_catalog/dags/providers/freesound_workflow.py
  openverse_catalog/dags/providers/jamendo_workflow.py
  openverse_catalog/dags/providers/metropolitan_museum_workflow.py
  openverse_catalog/dags/providers/phylopic_workflow.py
  openverse_catalog/dags/providers/rawpixel_workflow.py
  openverse_catalog/dags/providers/stocksnap_workflow.py
  openverse_catalog/dags/providers/wikimedia_ingestion_workflow.py
  openverse_catalog/dags/providers/wikimedia_workflow.py
  openverse_catalog/dags/providers/wordpress_workflow.py
  openverse_catalog/templates/workflow.py_template
  requirements_dev.txt
  requirements_prod.txt
  tests/dags/common/loader/test_paths.py
  tests/dags/common/loader/test_sql.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#309 Disable TSV loader scheduling
  openverse_catalog/dags/database/loader_workflow.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#310 Extend Jamendo's timeout to 24 hours
  openverse_catalog/dags/providers/jamendo_workflow.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#314 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
  .github/workflows/pr_ping.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx
