Repository WordPress/openverse-catalog, pull requests merged in 2021-10, with the labels that each got.

#198 Organize & document `justfile`, fix issue with recreate command
  justfile
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#206 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#217 Move dev-specific services into compose overrides file
  .github/workflows/push_pull_request_test.yml
  openverse_catalog/docker-compose.override.yml
  openverse_catalog/docker-compose.yml
Labels: ✨ goal: improvement, 🤖 aspect: dx

#196 Add new columns to MediaStore and database
  openverse_catalog/dags/common/licenses/licenses.py
  openverse_catalog/dags/loader_workflow.py
  openverse_catalog/dags/provider_api_scripts/jamendo.py
  openverse_catalog/dags/provider_api_scripts/test_jamendo.py
  openverse_catalog/dags/storage/audio.py
  openverse_catalog/dags/storage/column_names.py
  openverse_catalog/dags/storage/columns.py
  openverse_catalog/dags/storage/db_columns.py
  openverse_catalog/dags/storage/image.py
  openverse_catalog/dags/storage/media.py
  openverse_catalog/dags/storage/test_audio.py
  openverse_catalog/dags/storage/test_columns.py
  openverse_catalog/dags/storage/test_image.py
  openverse_catalog/dags/storage/test_media.py
  openverse_catalog/dags/storage/tsv_columns.py
  openverse_catalog/dags/util/loader/ingestion_column.py
  openverse_catalog/dags/util/loader/loader.py
  openverse_catalog/dags/util/loader/paths.py
  openverse_catalog/dags/util/loader/sql.py
  openverse_catalog/dags/util/loader/test_ingestion_column.py
  openverse_catalog/dags/util/loader/test_paths.py
  openverse_catalog/dags/util/loader/test_resources/foreign_identifier_duplicate.tsv
  openverse_catalog/dags/util/loader/test_resources/foreign_identifier_missing.tsv
  openverse_catalog/dags/util/loader/test_resources/foreign_landing_url_missing.tsv
  openverse_catalog/dags/util/loader/test_resources/license_missing.tsv
  openverse_catalog/dags/util/loader/test_resources/malformed_less_than_max_rows.tsv
  openverse_catalog/dags/util/loader/test_resources/malformed_max_rows.tsv
  openverse_catalog/dags/util/loader/test_resources/malformed_more_than_max_rows.tsv
  openverse_catalog/dags/util/loader/test_resources/new_columns_crawl.tsv
  openverse_catalog/dags/util/loader/test_resources/new_columns_papis.tsv
  openverse_catalog/dags/util/loader/test_resources/none_missing.tsv
  openverse_catalog/dags/util/loader/test_resources/old_columns_crawl.tsv
  openverse_catalog/dags/util/loader/test_resources/old_columns_papis.tsv
  openverse_catalog/dags/util/loader/test_resources/url_missing.tsv
  openverse_catalog/dags/util/loader/test_sql.py
  openverse_catalog/dags/util/pg_cleaner.py
  openverse_catalog/dags/util/popularity/sql.py
  openverse_catalog/dags/util/test_pg_cleaner.py
  openverse_catalog/dags/util/test_resources/image_table_sample.tsv
  openverse_catalog/dags/util/test_resources/multi_prov.tsv
  openverse_catalog/dags/util/test_tsv_cleaner.py
  openverse_catalog/dags/util/tsv_cleaner.py
  openverse_catalog/local_postgres/0003_openledger_image_schema.sql
  openverse_catalog/local_postgres/0004_openledger_image_view.sql
  openverse_catalog/local_postgres/0006_openledger_audio_schema.sql
  openverse_catalog/local_postgres/0007_openledger_audio_view.sql
Labels: 🌟 goal: addition, 💻 aspect: code

#274 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_ping.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx
