Repository WordPress/openverse-catalog, pull requests merged in 2022-05, with the labels that each got.

#493 Recreate the audioset matview after full popularity recalculation
  env.template
  openverse_catalog/dags/common/popularity/sql.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#500 Add human readable description for durations under 1 second
  openverse_catalog/dags/common/loader/reporting.py
  tests/dags/common/loader/test_reporting.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#501 Don't delete custom pools during test cleanup
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#496 Merge popularity calculations and data refresh into a single DAG
  openverse_catalog/dags/common/constants.py
  openverse_catalog/dags/common/popularity/operators.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_task_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/data_refresh/refresh_popularity_metrics_task_factory.py
  openverse_catalog/dags/data_refresh/refresh_view_data_task_factory.py
  openverse_catalog/dags/database/refresh_all_audio_popularity_data.py
  openverse_catalog/dags/database/refresh_all_image_popularity_data.py
  openverse_catalog/dags/database/refresh_audio_view_data.py
  openverse_catalog/dags/database/refresh_image_view_data.py
  tests/dags/data_refresh/test_dag_factory.py
  tests/dags/test_dag_parsing.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code, 🐍 tech: python, 🔧 tech: airflow

#508 Retry flaky request when Smithsonian provider script detects no unit codes
  openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py
  tests/dags/providers/provider_api_scripts/test_smithsonian.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#502 Upgrade Airflow to 2.3, python to 3.10
  docker/airflow/Dockerfile
  docker/airflow/wait_for_db.py
  env.template
  openverse_catalog/dags/common/provider_dag_factory.py
  requirements_prod.txt
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#507 Generate DAGs to recreate popularity calculations using a factory
  openverse_catalog/dags/common/popularity/operators.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/database/recreate_audio_popularity_calculation.py
  openverse_catalog/dags/database/recreate_image_popularity_calculation.py
  openverse_catalog/dags/database/recreate_popularity_calculation_dag_factory.py
  tests/dags/test_dag_parsing.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code, 🔧 tech: airflow

#514 airflow dockerfile: set `PYTHONPATH` to DAGs folder
  docker/airflow/Dockerfile
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#515 Simplify WP Photo Directory script and get missing authors
  openverse_catalog/dags/providers/provider_api_scripts/wordpress.py
  tests/dags/providers/provider_api_scripts/resources/wordpress/full_item.json
  tests/dags/providers/provider_api_scripts/resources/wordpress/full_item_details.json
  tests/dags/providers/provider_api_scripts/resources/wordpress/orientations_batch.json
  tests/dags/providers/provider_api_scripts/resources/wordpress/users_batch.json
  tests/dags/providers/provider_api_scripts/test_wordpress.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#516 Unconditionally destroy buckets after testing
  tests/dags/common/conftest.py
  tests/dags/common/loader/test_s3.py
  tests/dags/common/loader/test_sql.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code
