Repository WordPress/openverse-catalog, pull requests merged in 2022-09, with the labels that each got.

#708 Fix dagrun conf for provider scripts
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#701 Refactor Brooklyn Museum to use ProviderDataIngester
  openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/brooklynmuseum/expected_metadata.json
  tests/dags/providers/provider_api_scripts/test_brooklyn_museum.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#706 Always use Jamendo's "streaming" audio
  openverse_catalog/dags/providers/provider_api_scripts/jamendo.py
  tests/dags/providers/provider_api_scripts/test_jamendo.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#695 Allow string as exceptions in `on_failure_callback`
  openverse_catalog/dags/common/slack.py
  tests/dags/common/test_slack.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#614 Refactor Wikimedia Commons to use ProviderDataIngester
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/wikimedia/audio_filedata_ogg.json
  tests/dags/providers/provider_api_scripts/resources/wikimedia/audio_filedata_wav.json
  tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#713 Remove error swallowing during ingestion
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#711 Add `DEPLOYMENT.md` & deployment-related files
  DEPLOY.md
  DEPLOYMENT.md
  README.md
  dag-sync.sh
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#709 Add none check for Cleveland `image_data`
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
Labels: bug, 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#731 Bump Airflow version to 2.3.4
  docker/airflow/Dockerfile
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  requirements_prod.txt
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Labels: dependencies, 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#718 Add spellcheck to pre-commit config
  .pre-commit-config.yaml
  dag-sync.sh
  docker/airflow/entrypoint.sh
  tests/dags/providers/provider_api_scripts/resources/wikimedia/prettify.sh
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#618 Update reingestion workflows to load and report data
  DAGs.md
  openverse_catalog/dags/common/helpers.py
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_reingestion_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
  openverse_catalog/dags/providers/provider_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/common/loader/test_reporting.py
  tests/dags/common/test_helpers.py
  tests/dags/providers/test_factory_utils.py
  tests/dags/providers/test_provider_dag_factory.py
  tests/dags/test_dag_parsing.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 🛠 goal: fix

#644 Use Airflow variable to omit DAGs from any Slack notification
  DAGs.md
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/record_reporting.py
  openverse_catalog/dags/database/report_pending_reported_media.py
  openverse_catalog/dags/maintenance/check_silenced_dags.py
  openverse_catalog/dags/maintenance/check_silenced_dags/check_silenced_dags.py
  openverse_catalog/dags/maintenance/check_silenced_dags/check_silenced_dags_dag.py
  tests/dags/common/loader/test_reporting.py
  tests/dags/common/test_slack.py
  tests/dags/data_refresh/test_record_reporting.py
  tests/dags/maintenance/test_check_silenced_dags.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#737 Bump Airflow to 2.4.0, standardize version bump process
  .github/workflows/ci_cd.yml
  DAGs.md
  docker-compose.override.yml
  docker/airflow/Dockerfile
  env.template
  justfile
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/commoncrawl/sync_commoncrawl_workflow.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/database/loader_workflow.py
  openverse_catalog/dags/database/recreate_popularity_calculation_dag_factory.py
  openverse_catalog/dags/database/report_pending_reported_media.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/maintenance/check_silenced_dags.py
  openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py
  openverse_catalog/dags/oauth2/authorize_dag.py
  openverse_catalog/dags/oauth2/token_refresh_dag.py
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  pytest.ini
  requirements_prod.txt
  tests/dags/common/operators/test_postgres_result.py
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
  tests/dags/providers/test_factory_utils.py
  tests/utilities/dag_doc_gen/test_dag_doc_generation.py
Labels: 🟥 priority: critical, 💻 aspect: code, 🧰 goal: internal improvement

#739 Add tags option for provider workflows & "legacy-ingestion" tag
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx, 🔧 tech: airflow

#743 Default unfurling of links and media to False in Slack notifications
  openverse_catalog/dags/common/slack.py
  tests/dags/common/test_slack.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#742 Refactor SMK script to use the `ProviderDataIngester` class
  openverse_catalog/dags/providers/provider_api_scripts/smk.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/smk/item_with_alternative_images.json
  tests/dags/providers/provider_api_scripts/resources/smk/items_batch.json
  tests/dags/providers/provider_api_scripts/resources/smk/response_failure.json
  tests/dags/providers/provider_api_scripts/resources/smk/response_success.json
  tests/dags/providers/provider_api_scripts/test_smk.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#740 Add dependabot config
  .github/dependabot.yml
  justfile
  requirements.txt
  requirements_tooling.txt
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code
