Repository WordPress/openverse-catalog, pull requests merged in 2022-04, with the labels that each got.

#463 Upgrade black to 22.3.0
  .pre-commit-config.yaml
  openverse_catalog/dags/retired/common/pg_cleaner.py
  requirements.txt
  tests/dags/common/storage/test_columns.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#460 Use safe_search param to restrict results from Flickr
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  tests/dags/providers/provider_api_scripts/test_flickr.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code, ☁️ provider: images

#458 Adjust timeouts for Data Refresh `wait_for_completion` step
  openverse_catalog/dags/data_refresh/dag_factory.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code, 🔧 tech: airflow

#467 Re-introduce pytest-socket
  openverse_catalog/dags/common/urls.py
  pytest.ini
  requirements_dev.txt
  tests/dags/common/conftest.py
  tests/dags/common/loader/test_smithsonian_unit_codes.py
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
  tests/dags/common/test_urls.py
  tests/dags/conftest.py
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#442 Show duplicate record count in completion slack message
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/common/provider_dag_factory.py
  tests/dags/common/loader/test_reporting.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#472 Rename Thingiverse.py to thingiverse.py
  openverse_catalog/dags/providers/provider_api_scripts/thingiverse.py
Labels: 🚦 status: awaiting triage

#471 Improved load reporting
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/common/provider_dag_factory.py
  tests/dags/common/loader/test_loader.py
  tests/dags/common/loader/test_reporting.py
  tests/dags/common/loader/test_sql.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#474 Change docker-compose restart policy for local development
  docker-compose.override.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#452 Update Smithsonian Unit code checker DAG to alert to Slack
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/common/loader/smithsonian_unit_codes.py
  openverse_catalog/dags/providers/check_new_smithsonian_unit_codes_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py
  tests/dags/common/loader/test_smithsonian_unit_codes.py
  tests/dags/providers/provider_api_scripts/test_smithsonian.py
  tests/dags/test_dag_parsing.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#479 Fix `alt_files` duplicates
  openverse_catalog/dags/common/storage/columns.py
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#475 Wikimedia: Catch bit rates that are greater than the int max
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#480 Make Airflow connection variables easier to read
  docker/airflow/entrypoint.sh
  env.template
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#492 Enable reporting when there is no data to load
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
  tests/dags/common/loader/test_reporting.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
