Repository WordPress/openverse-catalog, pull requests merged in 2022-02, with the labels that each got.

#355 Updated user agent for Wikimedia Commons #140
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#359 Differentiate between slack channels
  env.template
  openverse_catalog/dags/common/slack.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#362 Use Airflow Variables for storing API keys
  env.template
  openverse_catalog/dags/providers/provider_api_scripts/Thingiverse.py
  openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/europeana.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  openverse_catalog/dags/providers/provider_api_scripts/jamendo.py
  openverse_catalog/dags/providers/provider_api_scripts/nypl.py
  openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py
  openverse_catalog/dags/providers/provider_api_scripts/walters_art_museum.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#357 Trigger TSV loading immediately after workflow
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/paths.py
  openverse_catalog/dags/common/loader/s3.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/database/loader_workflow.py
  openverse_catalog/dags/providers/freesound_workflow.py
  openverse_catalog/dags/providers/jamendo_workflow.py
  openverse_catalog/dags/providers/wikimedia_workflow.py
  tests/dags/common/loader/test_s3.py
  tests/dags/common/loader/test_sql.py
  tests/dags/common/storage/test_audio.py
  tests/dags/common/storage/test_media.py
  tests/dags/common/test_dag_factory.py
  tests/dags/common/test_resources/fake_provider_module.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#369 Add slack message on TSV load complete
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/common/slack.py
  tests/dags/common/loader/test_reporting.py
  tests/dags/common/test_dag_factory.py
  tests/dags/common/test_slack.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#361 Reconfigure retries & timeouts for typical ingestion DAGs
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/providers/brooklyn_museum_workflow.py
  openverse_catalog/dags/providers/finnish_museums_workflow.py
  openverse_catalog/dags/providers/jamendo_workflow.py
  openverse_catalog/dags/providers/museum_victoria_workflow.py
  openverse_catalog/dags/providers/nypl_workflow.py
  openverse_catalog/dags/providers/science_museum_workflow.py
  openverse_catalog/dags/providers/smithsonian_workflow.py
  openverse_catalog/dags/providers/statens_museum_workflow.py
  openverse_catalog/dags/providers/walters_workflow.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#372 Update Airflow to 2.2.4
  docker/airflow/Dockerfile
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  requirements_prod.txt
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#382 Report the environment in TSV loader Slack notifications
  openverse_catalog/dags/common/slack.py
  tests/dags/common/test_slack.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code
