Repository WordPress/openverse-catalog, pull requests merged in 2022-03, with the labels that each got.

#404 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/label_new_pr.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#409 Group test runs by module or class
  pytest.ini
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#402 Make 'sound' category more specific
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟥 priority: critical, ✨ goal: improvement, 💻 aspect: code

#395 Handle duplicate keys in load_data task
  openverse_catalog/dags/common/loader/sql.py
  tests/dags/common/loader/test_sql.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code, 💾 tech: postgres

#412 Add OFEO-SG subprovider
  openverse_catalog/dags/common/loader/provider_details.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#414 Update API requests for Museum Victoria DAG
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  tests/dags/providers/provider_api_scripts/test_museum_victoria.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#416 Fix schedule intervals on Cleveland Museum & Wikimedia Commons
  openverse_catalog/dags/providers/cleveland_museum_workflow.py
  openverse_catalog/dags/providers/wikimedia_workflow.py
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#413 Add ConnectionError to acceptable flaky exceptions for Freesound
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#415 Reduce noise in NYPL ingestion
  openverse_catalog/dags/providers/provider_api_scripts/nypl.py
  tests/dags/providers/provider_api_scripts/test_nypl.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#418 Fix invalid license urls from Finnish Museum API
  openverse_catalog/dags/providers/finnish_museums_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/finnish_museums.py
  tests/dags/providers/provider_api_scripts/test_finnish_museums.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#417 Use published Docker image in primary docker-compose.yml
  docker-compose.override.yml
  docker-compose.yml
  env.template
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#421 Enable XCom pickling in Airflow
  docker/airflow/Dockerfile
  openverse_catalog/dags/common/dag_factory.py
  openverse_catalog/dags/common/loader/reporting.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code, 🐳 tech: docker

#422 Round duration for provider ingestion completion message
  openverse_catalog/dags/common/loader/reporting.py
  tests/dags/common/loader/test_reporting.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#424 Add LRU cache to `is_valid_license_info`
  openverse_catalog/dags/common/licenses/licenses.py
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#423 Change PhyloPic date range & schedule interval
  openverse_catalog/dags/providers/phylopic_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/phylopic.py
  tests/dags/providers/provider_api_scripts/test_phylopic.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#397 Add data refresh to Airflow
  env.template
  openverse_catalog/dags/common/constants.py
  openverse_catalog/dags/common/provider_dag_factory.py
  openverse_catalog/dags/common/sensors/__init__.py
  openverse_catalog/dags/common/sensors/single_run_external_dags_sensor.py
  openverse_catalog/dags/data_refresh/__init__.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/providers/brooklyn_museum_workflow.py
  openverse_catalog/dags/providers/cleveland_museum_workflow.py
  openverse_catalog/dags/providers/europeana_ingestion_workflow.py
  openverse_catalog/dags/providers/europeana_workflow.py
  openverse_catalog/dags/providers/finnish_museums_workflow.py
  openverse_catalog/dags/providers/flickr_ingestion_workflow.py
  openverse_catalog/dags/providers/flickr_workflow.py
  openverse_catalog/dags/providers/freesound_workflow.py
  openverse_catalog/dags/providers/jamendo_workflow.py
  openverse_catalog/dags/providers/metropolitan_museum_workflow.py
  openverse_catalog/dags/providers/museum_victoria_workflow.py
  openverse_catalog/dags/providers/nypl_workflow.py
  openverse_catalog/dags/providers/phylopic_workflow.py
  openverse_catalog/dags/providers/rawpixel_workflow.py
  openverse_catalog/dags/providers/science_museum_workflow.py
  openverse_catalog/dags/providers/smithsonian_workflow.py
  openverse_catalog/dags/providers/statens_museum_workflow.py
  openverse_catalog/dags/providers/stocksnap_workflow.py
  openverse_catalog/dags/providers/walters_workflow.py
  openverse_catalog/dags/providers/wikimedia_ingestion_workflow.py
  openverse_catalog/dags/providers/wikimedia_workflow.py
  openverse_catalog/dags/providers/wordpress_workflow.py
  openverse_catalog/templates/workflow.py_template
  tests/dags/common/sensors/__init__.py
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
  tests/dags/common/test_provider_dag_factory.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code, 🔧 tech: airflow

#440 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#441 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#434 Send single slack notification per provider on TSV load complete
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/provider_dag_factory.py
  tests/dags/common/loader/test_reporting.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#444 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/discussion.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#443 Handle case where Wikimedia has no audio metadata
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#455 Remove `apt upgrade` from PG image, upgrade to 13.6
  .github/workflows/ci_cd.yml
  docker/local_postgres/Dockerfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx
