Repository WordPress/openverse-catalog, pull requests merged in 2022-10, with the labels that each got.

#763 Remove periods after URLs in log lines.
  openverse_catalog/dags/common/licenses/licenses.py
  openverse_catalog/dags/common/requester.py
  openverse_catalog/dags/common/urls.py
  openverse_catalog/dags/providers/provider_api_scripts/modules/etlMods.py
  openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#744 Improved data refresh status reporting
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/refresh_popularity_metrics_task_factory.py
  openverse_catalog/dags/data_refresh/refresh_view_data_task_factory.py
  openverse_catalog/dags/data_refresh/reporting.py
  tests/dags/data_refresh/test_dag_factory.py
  tests/dags/data_refresh/test_reporting.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#765 Add user agent to StockSnap header and use header in requests by default
  openverse_catalog/dags/common/requester.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
  tests/dags/common/test_requester.py
  tests/dags/providers/provider_api_scripts/test_stocksnap.py
Labels: 🚦 status: awaiting triage

#769 Fix italics for duration disclosure
  openverse_catalog/dags/common/loader/reporting.py
Labels: bug, 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#780 Increase dependabot PR limit to 10
  .github/dependabot.yml
Labels: 🟨 priority: medium, ✨ goal: improvement, 🤖 aspect: dx

#770 Add concurrency settings for workflow
  .github/workflows/ci_cd.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#788 Disable email on failure by default
  openverse_catalog/dags/common/constants.py
Labels: 🟩 priority: low, 🕹 aspect: interface, 🧰 goal: internal improvement

#741 Refactor Jamendo to use the ProviderDataIngester
  openverse_catalog/dags/providers/provider_api_scripts/jamendo.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/jamendo/last_page.json
  tests/dags/providers/provider_api_scripts/resources/jamendo/page1.json
  tests/dags/providers/provider_api_scripts/resources/jamendo/page2.json
  tests/dags/providers/provider_api_scripts/test_jamendo.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#786 Retire Walters Art Museum provider script
  DAGs.md
  env.template
  openverse_catalog/dags/providers/provider_workflows.py
  openverse_catalog/dags/retired/providers/provider_api_scripts/walters.py
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/full_image_object.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/items_list_example.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_creator_info.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_foreign_id.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_foreign_landing_url.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_image_url.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_meta_data.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_thumbnail_url.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/no_title.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/partial_meta_data.json
  tests/dags/providers/provider_api_scripts/resources/waltersartmuseum/walters_full_response_example.json
  tests/dags/providers/provider_api_scripts/test_walters.py
Labels: 🟨 priority: medium, 🕹 aspect: interface, 🧰 goal: internal improvement

#746 Refactor Freesound to use ProviderDataIngester
  DAGs.md
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#789 Retire TSV loading workflow
  DAGs.md
  openverse_catalog/dags/common/loader/paths.py
  openverse_catalog/dags/retired/database/loader_workflow.py
  tests/dags/common/loader/test_paths.py
  tests/dags/test_dag_parsing.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#804 Respect the ingestion limit if ingest_records is called multiple times
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#801 Standardize Airflow Variable names to uppercase
  DAGs.md
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/maintenance/check_silenced_dags.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  tests/dags/common/test_slack.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#807 Use English for SMK results
  openverse_catalog/dags/providers/provider_api_scripts/smk.py
  tests/dags/providers/provider_api_scripts/test_smk.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#806 Allow default retry count to be determined by environment variable
  env.template
  openverse_catalog/dags/common/constants.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#792 Add condition to not notify slack when don't have files in dags folder
  dag-sync.sh
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#630 Refactor NYPL script to use ProviderDataIngester class
  openverse_catalog/dags/providers/provider_api_scripts/nypl.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/nypl/metadata.json
  tests/dags/providers/provider_api_scripts/test_nypl.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#790 Add docs and template ProviderDataIngester
  justfile
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/docs/adding_a_new_provider.md
  openverse_catalog/docs/assets/provider_dags/multi_media_dag.png
  openverse_catalog/docs/assets/provider_dags/simple_dag.png
  openverse_catalog/docs/data_models.md
  openverse_catalog/docs/provider_data_ingester_faq.md
  openverse_catalog/templates/__init__.py
  openverse_catalog/templates/create_provider_ingester.py
  openverse_catalog/templates/template_provider.py_template
  openverse_catalog/templates/template_test.py_template
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
  tests/templates/test_create_provider_ingester.py
Labels: documentation, 🟧 priority: high, ✨ goal: improvement

#747 Refactor Phylopic to use ProviderDataIngester
  DAGs.md
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/providers/provider_api_scripts/phylopic.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/phylopic/total_images_example.json
  tests/dags/providers/provider_api_scripts/test_phylopic.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#819 Add reingestion workflow for Metropolitan
  DAGs.md
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#818 Respect ingestion limit in process_batch
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#809 Refactor Flickr to use ProviderDataIngester
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/flickr/total_pages_but_no_image_list.json
  tests/dags/providers/provider_api_scripts/test_flickr.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#837 Restore the old dag_id for wikimedia_reingestion_workflow
  DAGs.md
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#833 Retire Thingiverse, etlMods, commoncrawl ETL
  openverse_catalog/dags/retired/common/etl/__init__.py
  openverse_catalog/dags/retired/common/etl/bootstrap/config-py27.sh
  openverse_catalog/dags/retired/common/etl/scripts/ExtractCCLinks.py
  openverse_catalog/dags/retired/common/etl/scripts/__init__.py
  openverse_catalog/dags/retired/providers/provider_api_scripts/modules/__init__.py
  openverse_catalog/dags/retired/providers/provider_api_scripts/modules/etlMods.py
  openverse_catalog/dags/retired/providers/provider_api_scripts/thingiverse.py
  tests/dags/providers/provider_api_scripts/modules/__init__.py
  tests/dags/providers/provider_api_scripts/modules/test_etlMods.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#795 Refactor Rawpixel to use `ProviderDataIngester`
  DAGs.md
  docker/local_postgres/0004_openledger_image_view.sql
  env.template
  openverse_catalog/dags/common/licenses/__init__.py
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/rawpixel/public_domain_response.json
  tests/dags/providers/provider_api_scripts/resources/rawpixel/total_images_but_pinterest_descr_example.json
  tests/dags/providers/provider_api_scripts/resources/rawpixel/total_images_example.json
  tests/dags/providers/provider_api_scripts/test_rawpixel.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#812 Refactor Smithsonian Museum to use `ProviderDataIngester` class
  DAGs.md
  openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/smithsonian/actual_record_data.json
  tests/dags/providers/provider_api_scripts/resources/smithsonian/actual_response.json
  tests/dags/providers/provider_api_scripts/resources/smithsonian/actual_response2.json
  tests/dags/providers/provider_api_scripts/test_smithsonian.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#821 Refactor Europeana to use `ProviderDataIngester`
  openverse_catalog/dags/providers/provider_api_scripts/europeana.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/provider_data_ingester/mock_provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_europeana.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#835 Refactor WordPress to use `ProviderDataIngester`
  openverse_catalog/dags/providers/provider_api_scripts/phylopic.py
  openverse_catalog/dags/providers/provider_api_scripts/wordpress.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/test_wordpress.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#830 Add reingestion DAG for Phylopic
  DAGs.md
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#848 Fix Europeana success test, activate reingestion workflows
  openverse_catalog/dags/providers/provider_api_scripts/europeana.py
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/europeana/europeana_example.json
  tests/dags/providers/provider_api_scripts/resources/europeana/europeana_image_list.json
  tests/dags/providers/provider_api_scripts/resources/europeana/image_data_example.json
  tests/dags/providers/provider_api_scripts/test_europeana.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#849 Remove legacy provider DAG logic
  DAGs.md
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
  openverse_catalog/dags/providers/provider_workflows.py
  openverse_catalog/docs/adding_a_new_provider.md
  tests/dags/providers/test_factory_utils.py
  tests/dags/providers/test_provider_dag_factory.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code
