Repository WordPress/openverse-catalog, pull requests merged in 2022-08, with the labels that each got.

#632 Partition TSVs by date
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/providers/test_factory_utils.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#635 Use the default provider categories during ingestion
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
  tests/dags/common/storage/test_media.py
  tests/dags/providers/provider_api_scripts/test_stocksnap.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#636 Data refresh record difference reporting
  openverse_catalog/dags/common/constants.py
  openverse_catalog/dags/common/operators/__init__.py
  openverse_catalog/dags/common/operators/postgres_result.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/record_reporting.py
  openverse_catalog/dags/database/report_pending_reported_media.py
  tests/dags/common/operators/__init__.py
  tests/dags/common/operators/test_postgres_result.py
  tests/dags/data_refresh/test_record_reporting.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#652 Fix typo in README
  README.md
Labels: 🚦 status: awaiting triage

#643 Omit DAGs that are known to fail from alerts
  openverse_catalog/dags/common/github.py
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/database/report_pending_reported_media.py
  openverse_catalog/dags/maintenance/check_silenced_dags/check_silenced_dags.py
  openverse_catalog/dags/maintenance/check_silenced_dags/check_silenced_dags_dag.py
  tests/dags/common/test_slack.py
  tests/dags/maintenance/test_check_silenced_dags.py
  tests/factories/github/__init__.py
  tests/factories/github/issue.json
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#651 Only delete dag runs/task instances during testing that match pattern
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#649 Automatic DAG documentation generation
  .github/workflows/ci_cd.yml
  DAGs.md
  README.md
  justfile
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/utilities/README.md
  openverse_catalog/utilities/__init__.py
  openverse_catalog/utilities/dag_doc_gen/__init__.py
  openverse_catalog/utilities/dag_doc_gen/dag_doc_generation.py
  tests/utilities/dag_doc_gen/test_dag_doc_generation.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#645 Tighten exception handling, always flush buffer
  openverse_catalog/dags/common/licenses/licenses.py
  openverse_catalog/dags/common/requester.py
  openverse_catalog/dags/common/storage/columns.py
  openverse_catalog/dags/common/tsv_cleaner.py
  openverse_catalog/dags/common/urls.py
  openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/europeana.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/nypl.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
  openverse_catalog/dags/providers/provider_api_scripts/smk.py
  openverse_catalog/dags/providers/provider_api_scripts/wordpress.py
  tests/dags/common/test_urls.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#642 Re-ping if PR is updated and don't ping if 2 approvals exist
  openverse_catalog/dags/common/github.py
  openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py
  tests/dags/maintenance/test_pr_review_reminders.py
  tests/factories/github/__init__.py
  tests/factories/github/branch_protection.json
  tests/factories/github/comment.json
  tests/factories/github/pull.json
  tests/factories/github/review.json
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#662 Updates Handbook Link
  README.md
Labels: 🚦 status: awaiting triage

#650 Add configuration options to skip ingestion errors
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
  tests/dags/providers/test_factory_utils.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#656 Use Python 3.10 everywhere
  .github/workflows/ci_cd.yml
  docker-compose.override.yml
  docker/airflow/Dockerfile
  justfile
  openverse_catalog/templates/README.md
  openverse_catalog/templates/__init__.py
  openverse_catalog/templates/create_api_script.py
  openverse_catalog/templates/template_provider.py_template
  openverse_catalog/templates/template_test.py_template
  openverse_catalog/templates/workflow.py_template
  requirements_prod.txt
  tests/templates/test_create_api_script.py
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#660 Update audioset_view to use most recently updated f_id/provider pair
  docker/local_postgres/0007_openledger_audio_view.sql
  openverse_catalog/dags/common/popularity/sql.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#683 Add Openverse email to DAG default args
  openverse_catalog/dags/common/constants.py
Labels: 🟨 priority: medium, 🕹 aspect: interface, 🧰 goal: internal improvement

#549 Add iNaturalist.org metadata
  DAGs.md
  docker-compose.override.yml
  docker/local_postgres/0002_aws_s3_mock.sql
  justfile
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/create_schema.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/export_to_json.template.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/observations.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/observers.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/photos.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/taxa.sql
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/inaturalist/full_db_response.txt
  tests/dags/providers/provider_api_scripts/resources/inaturalist/pull_sample_records.py
  tests/dags/providers/provider_api_scripts/test_inaturalist.py
  tests/s3-data/inaturalist-open-data/observations.csv.gz
  tests/s3-data/inaturalist-open-data/observers.csv.gz
  tests/s3-data/inaturalist-open-data/photos.csv.gz
  tests/s3-data/inaturalist-open-data/taxa.csv.gz
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#678 Standardize on datetime over pendulum
  openverse_catalog/dags/providers/factory_utils.py
  tests/dags/common/operators/test_postgres_result.py
  tests/dags/providers/test_factory_utils.py
  tests/dags/providers/test_provider_dag_factory.py
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#677 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 🚦 status: awaiting triage

#691 Bump iNaturalist timeouts to 5 days
  openverse_catalog/dags/providers/provider_workflows.py
Labels: 🟥 priority: critical, ✨ goal: improvement, 🕹 aspect: interface

#654 Allow DAGs to silence only errors matching predicate
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/maintenance/check_silenced_dags/check_silenced_dags.py
  tests/dags/common/test_slack.py
  tests/dags/maintenance/test_check_silenced_dags.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#694 Always record provider run duration
  openverse_catalog/dags/providers/factory_utils.py
  tests/dags/providers/test_factory_utils.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#705 hardcodes the test ingestion limit to 1 000 000
  justfile
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#707 Initialize iNaturalist with dagrun conf
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
