Repository WordPress/openverse-catalog, pull requests merged in 2022-12, with the labels that each got.

#897 Add Rawpixel to image popularity recalculation logic
  docker/local_postgres/0007_openledger_audio_view.sql
  justfile
  openverse_catalog/dags/common/popularity/sql.py
  tests/dags/common/popularity/test_sql.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#908 Add DAG tag for showing dated vs full ingestion
  openverse_catalog/dags/providers/provider_dag_factory.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#905 Handle Science Museum errors with batches larger than 50 pages
  DAGs.md
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  tests/dags/providers/provider_api_scripts/test_science_museum.py
  tests/dags/providers/test_factory_utils.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#910 Replace deprecated `set-output` command
  .github/workflows/ci_cd.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#880 Allow overriding the date from the DagRun conf
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#879 Make Finnish DAG dated
  DAGs.md
  openverse_catalog/dags/providers/provider_api_scripts/finnish_museums.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/test_finnish_museums.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#916 Halt ingestion when WordPress Photo Directory reaches last page
  openverse_catalog/dags/providers/provider_api_scripts/wordpress.py
  tests/dags/providers/provider_api_scripts/test_wordpress.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#874 Use Airflow base Docker image
  README.md
  docker-compose.override.yml
  docker-compose.yml
  docker/airflow/Dockerfile
  docker/airflow/entrypoint.sh
  docker/airflow/wait_for_db.py
  env.template
  justfile
  openverse_catalog/templates/create_provider_ingester.py
  pytest.ini
  tests/templates/test_create_provider_ingester.py
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#914 Break load_from_s3 into separate tasks to fix duplicate reporting
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/common/loader/test_loader.py
  tests/dags/common/loader/test_sql.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#904 RDS Snapshot rotation DAG
  DAGs.md
  env.template
  openverse_catalog/dags/maintenance/check_silenced_dags.py
  openverse_catalog/dags/maintenance/rotate_db_snapshots.py
  tests/dags/maintenance/test_rotate_db_snapshots.py
  tests/dags/test_dag_parsing.py
Labels: 🚦 status: awaiting triage
