Repository WordPress/openverse-catalog, pull requests merged in 2022-11, with the labels that each got.

#851 Filter out the extra fields with no additional info in Cleveland Museum metadata
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
Labels: 🚦 status: awaiting triage

#850 Science Museum: Handle unrecognized licenses
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/license_source.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/no_license_no_legal.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/no_license_no_usage_terms.json
  tests/dags/providers/provider_api_scripts/test_science_museum.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#862 Remove unused arguments in MediaStore
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  tests/dags/common/storage/test_audio.py
  tests/dags/common/storage/test_media.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#866 Adding pyupgrade pre-commit hook
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  openverse_catalog/dags/common/helpers.py
  openverse_catalog/dags/common/licenses/licenses.py
  openverse_catalog/dags/common/loader/paths.py
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/common/log_cleanup.py
  openverse_catalog/dags/common/operators/postgres_result.py
  openverse_catalog/dags/common/sensors/single_run_external_dags_sensor.py
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/columns.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/common/storage/tsv_columns.py
  openverse_catalog/dags/common/storage/util.py
  openverse_catalog/dags/commoncrawl/commoncrawl_scripts/commoncrawl_s3_syncer/SyncImageProviders.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_task_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/maintenance/check_silenced_dags.py
  openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py
  openverse_catalog/dags/oauth2/oauth2.py
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  openverse_catalog/dags/providers/provider_api_scripts/jamendo.py
  openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py
  openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
  openverse_catalog/dags/providers/provider_workflows.py
  openverse_catalog/dags/retired/common/etl/scripts/ExtractCCLinks.py
  openverse_catalog/dags/retired/common/ingestion_column.py
  openverse_catalog/dags/retired/providers/provider_api_scripts/thingiverse.py
  tests/dags/common/test_resources/fake_provider_data_ingester.py
  tests/factories/github/__init__.py
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#868 Override `get_should_continue` for science museum ingester
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  tests/dags/providers/provider_api_scripts/test_science_museum.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#867 Unify pre-commit config across repos
  .github/ISSUE_TEMPLATE/image_provider_api_integration_request.yml
  .pre-commit-config.yaml
  docker-compose.override.yml
  docker-compose.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#865 Add `HEAD` requests support to `DelayedRequester`
  openverse_catalog/dags/common/requester.py
  openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
  openverse_catalog/dags/providers/provider_api_scripts/wordpress.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#872 Only report DAG sync when DAG files have changed
  dag-sync.sh
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#870 Retire Common Crawl module & DAGs
  DAGs.md
  README.md
  docker-compose.override.yml
  env.template
  openverse_catalog/dags/.airflowignore
  openverse_catalog/dags/retired/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/retired/commoncrawl/commoncrawl_scripts/commoncrawl_s3_syncer/SyncImageProviders.py
  openverse_catalog/dags/retired/commoncrawl/commoncrawl_scripts/scripts/merge_cc_tags.py
  openverse_catalog/dags/retired/commoncrawl/commoncrawl_utils.py
  openverse_catalog/dags/retired/commoncrawl/sync_commoncrawl_workflow.py
  tests/dags/common/etl/__init__.py
  tests/dags/common/etl/test_commoncrawl_utils.py
  tests/dags/common/loader/test_resources/new_columns_crawl.tsv
  tests/dags/common/loader/test_resources/new_columns_papis.tsv
  tests/dags/common/loader/test_resources/old_columns_crawl.tsv
  tests/dags/common/loader/test_resources/old_columns_papis.tsv
  tests/dags/test_dag_parsing.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface
