Repository WordPress/openverse-catalog, pull requests merged in 2022-07, with the labels that each got.

#610 Unify header added
  README.md
Labels: 🚦 status: awaiting triage

#612 Update Openverse URL in the user agent string
  openverse_catalog/dags/common/loader/provider_details.py
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#613 Add date range to ingestion load reports
  openverse_catalog/dags/common/loader/reporting.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/common/loader/test_reporting.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#627 Ignore DS_Store files
  .gitignore
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#602 Turn on catchup for dated DAGs to allow backfill
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#628 Patch Stocksnap tests that called out to external API
  tests/dags/providers/provider_api_scripts/test_stocksnap.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#620 Generate TSV filenames in separate step
  openverse_catalog/dags/common/constants.py
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/common/test_provider_dag_factory.py
  tests/dags/common/test_resources/fake_provider_data_ingester.py
  tests/dags/common/test_resources/fake_provider_module.py
  tests/dags/providers/test_factory_utils.py
  tests/dags/providers/test_provider_dag_factory.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#578 Update data refresh DAG to account for manual go-live
  openverse_catalog/dags/data_refresh/data_refresh_task_factory.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code, ⛔ status: blocked

#626 Adjust load data timeout and retries
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_ingestion_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_ingestion_workflows.py
  openverse_catalog/dags/providers/provider_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#629 Re-raise pytest-socket errors within DelayedRequester
  openverse_catalog/dags/common/requester.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#600 Refactor Museum Victoria to use ProviderDataIngester
  openverse_catalog/dags/common/requester.py
  openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/museumvictoria/image_data_success.json
  tests/dags/providers/provider_api_scripts/resources/museumvictoria/media_data_failure.json
  tests/dags/providers/provider_api_scripts/resources/museumvictoria/media_data_success.json
  tests/dags/providers/provider_api_scripts/resources/museumvictoria/record_data.json
  tests/dags/providers/provider_api_scripts/test_museum_victoria.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#576 Refactor Science museum to use ProviderDataIngester
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/license_source.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/measurements.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/no_license.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/no_license_no_legal.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/no_license_no_usage_terms.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/object_data.json
  tests/dags/providers/provider_api_scripts/resources/sciencemuseum/objects_data.json
  tests/dags/providers/provider_api_scripts/test_science_museum.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#634 Only drop load table if it exists
  .github/workflows/ci_cd.yml
  README.md
  openverse_catalog/dags/common/loader/sql.py
  tests/conftest.py
  tests/dags/providers/test_provider_dag_factory.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
