Repository WordPress/openverse-catalog, pull requests merged in 2022-06, with the labels that each got.

#526 Remove thumbnails from images
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/tsv_cleaner.py
  openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/europeana.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/jamendo.py
  openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum_of_art.py
  openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py
  openverse_catalog/dags/providers/provider_api_scripts/nypl.py
  openverse_catalog/dags/providers/provider_api_scripts/phylopic.py
  openverse_catalog/dags/providers/provider_api_scripts/raw_pixel.py
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py
  openverse_catalog/dags/providers/provider_api_scripts/smk.py
  openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
  openverse_catalog/dags/providers/provider_api_scripts/walters_art_museum.py
  tests/dags/common/storage/test_image.py
  tests/dags/common/storage/test_media.py
  tests/dags/common/test_tsv_cleaner.py
  tests/dags/providers/provider_api_scripts/resources/example_output/clevelandmuseum_1551823168.tsv
  tests/dags/providers/provider_api_scripts/resources/museumvictoria/image_data_success.json
  tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_hq.json
  tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_legacy.json
  tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_partial.json
  tests/dags/providers/provider_api_scripts/test_brooklyn_museum.py
  tests/dags/providers/provider_api_scripts/test_europeana.py
  tests/dags/providers/provider_api_scripts/test_flickr.py
  tests/dags/providers/provider_api_scripts/test_metropolitan_museum_of_art.py
  tests/dags/providers/provider_api_scripts/test_nypl.py
  tests/dags/providers/provider_api_scripts/test_phylopic.py
  tests/dags/providers/provider_api_scripts/test_raw_pixel.py
  tests/dags/providers/provider_api_scripts/test_science_museum.py
  tests/dags/providers/provider_api_scripts/test_smithsonian.py
  tests/dags/providers/provider_api_scripts/test_smk.py
  tests/dags/providers/provider_api_scripts/test_stocksnap.py
  tests/dags/providers/provider_api_scripts/test_walters_art_museum.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#544 Correct order of None handling in Cleveland provider script
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum_of_art.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum_of_art.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#513 Add DAG to report reported media pending review
  env.template
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/database/report_pending_reported_media.py
  tests/dags/common/test_slack.py
  tests/dags/database/__init__.py
  tests/dags/database/test_report_pending_reported_media.py
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code, 🐍 tech: python, 🔧 tech: airflow

#551 Create DAG objects at top level
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/commoncrawl/sync_commoncrawl_workflow.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/database/loader_workflow.py
  openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py
  openverse_catalog/dags/oauth2/authorize_dag.py
  openverse_catalog/dags/oauth2/token_refresh_dag.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#545 Add a helper function to extract extension from the media URL
  openverse_catalog/dags/common/extensions.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  tests/dags/common/storage/test_media.py
  tests/dags/common/test_extensions.py
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code, data normalization

#540 Consolidate provider workflows using dynamic DAGs and dataclasses
  openverse_catalog/dags/common/helpers.py
  openverse_catalog/dags/common/provider_dag_factory.py
  openverse_catalog/dags/providers/brooklyn_museum_workflow.py
  openverse_catalog/dags/providers/cleveland_museum_workflow.py
  openverse_catalog/dags/providers/europeana_ingestion_workflow.py
  openverse_catalog/dags/providers/europeana_workflow.py
  openverse_catalog/dags/providers/finnish_museums_workflow.py
  openverse_catalog/dags/providers/flickr_ingestion_workflow.py
  openverse_catalog/dags/providers/flickr_workflow.py
  openverse_catalog/dags/providers/freesound_workflow.py
  openverse_catalog/dags/providers/jamendo_workflow.py
  openverse_catalog/dags/providers/metropolitan_museum_workflow.py
  openverse_catalog/dags/providers/museum_victoria_workflow.py
  openverse_catalog/dags/providers/nypl_workflow.py
  openverse_catalog/dags/providers/phylopic_workflow.py
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
  openverse_catalog/dags/providers/provider_api_scripts/walters.py
  openverse_catalog/dags/providers/provider_ingestion_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_ingestion_workflows.py
  openverse_catalog/dags/providers/provider_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
  openverse_catalog/dags/providers/rawpixel_workflow.py
  openverse_catalog/dags/providers/science_museum_workflow.py
  openverse_catalog/dags/providers/smithsonian_workflow.py
  openverse_catalog/dags/providers/smk_workflow.py
  openverse_catalog/dags/providers/stocksnap_workflow.py
  openverse_catalog/dags/providers/walters_workflow.py
  openverse_catalog/dags/providers/wikimedia_ingestion_workflow.py
  openverse_catalog/dags/providers/wikimedia_workflow.py
  openverse_catalog/dags/providers/wordpress_workflow.py
  tests/dags/common/test_helpers.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
  tests/dags/providers/provider_api_scripts/test_metropolitan_museum.py
  tests/dags/providers/provider_api_scripts/test_rawpixel.py
  tests/dags/providers/provider_api_scripts/test_walters.py
  tests/dags/test_dag_parsing.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#556 Add flag to strip slash in urls while validating
  openverse_catalog/dags/common/urls.py
  tests/dags/common/test_urls.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#542 Add `filetype` and `filesize` to SMK script
  openverse_catalog/dags/providers/provider_api_scripts/smk.py
  tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_hq.json
  tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_legacy.json
  tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_partial.json
  tests/dags/providers/provider_api_scripts/test_smk.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code, data normalization

#537 Add `filetype` and `filesize` to Cleveland Museum of Art API script
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py
  tests/dags/common/storage/test_media.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code, data normalization

#566 Fix module import for PR review reminder DAG
  openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py
  tests/dags/test_dag_parsing.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#565 Add audio_set_foreign_identifier to the audio materialized view
  docker/local_postgres/0007_openledger_audio_view.sql
  openverse_catalog/dags/common/popularity/sql.py
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#570 Post comments using JSON instead of form data
  openverse_catalog/dags/common/github.py
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#547 Add `filetype` to Phylopic script
  openverse_catalog/dags/providers/provider_api_scripts/phylopic.py
  tests/dags/providers/provider_api_scripts/test_phylopic.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code, data normalization

#555 Add base class for Provider API scripts
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/common/storage/util.py
  openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  openverse_catalog/dags/providers/provider_ingestion_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_workflow_dag_factory.py
  openverse_catalog/dags/providers/provider_workflows.py
  openverse_catalog/templates/workflow.py_template
  tests/dags/common/storage/test_image.py
  tests/dags/common/storage/test_media.py
  tests/dags/common/storage/test_util.py
  tests/dags/common/test_provider_dag_factory.py
  tests/dags/providers/provider_api_scripts/resources/clevelandmuseum/expected_batch_data.json
  tests/dags/providers/provider_api_scripts/resources/clevelandmuseum/image_type_print.json
  tests/dags/providers/provider_api_scripts/resources/clevelandmuseum/image_type_web.json
  tests/dags/providers/provider_api_scripts/resources/provider_data_ingester/complete_response.json
  tests/dags/providers/provider_api_scripts/resources/provider_data_ingester/mock_provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement
