Repository WordPress/openverse-catalog, pull requests merged in 2022-01, with the labels that each got.

#317 🔄 Synced file(s) with WordPress/openverse
  .github/release-drafter.yml
  .github/release_drafter.yml
  .github/workflows/draft_release.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#318 Make commoncrawl bucket configurable, change default
  env.template
  openverse_catalog/dags/common/etl/scripts/ExtractCCLinks.py
  openverse_catalog/dags/commoncrawl/commoncrawl_etl.py
  openverse_catalog/dags/commoncrawl/commoncrawl_scripts/commoncrawl_s3_syncer/SyncImageProviders.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#312 Change request info log to debug to prevent spam
  openverse_catalog/dags/common/requester.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#311 Set default timeout to 12 hours
  openverse_catalog/dags/common/dag_factory.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#320 Add audioset_view to catalog DDL
  docker/local_postgres/0007_openledger_audio_view.sql
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#327 Properly handle "None" values returned from Freesound API
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#328 Fix inconsistent alignment in slack message text
  openverse_catalog/dags/common/slack.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#332 Set up CI/CD with ghcr.io
  .github/workflows/ci_cd.yml
  .github/workflows/lint.yml
  .github/workflows/push_pull_request_test.yml
  README.md
  docker-compose.yml
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#330 Freesound SSLError fix
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  requirements_prod.txt
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#341 Change minio ports from 500X to 501X
  README.md
  docker-compose.override.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#344 Remove buckets after testing
  tests/dags/common/conftest.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
