Repository WordPress/openverse-catalog, pull requests merged in 2023-01, with the labels that each got.

#946 Adjust year ranges for Science Museum
  openverse_catalog/dags/providers/provider_api_scripts/science_museum.py
  tests/dags/providers/provider_api_scripts/test_science_museum.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#928 Handle Freesound 404s when fetching audio sets
  DAGs.md
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#937 Allow no content responses from GitHub
  openverse_catalog/dags/common/github.py
  openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py
  requirements_dev.txt
  tests/dags/common/test_github.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#958 Met Museum Reingestion timeout set to 16 hours
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#939 Upgrade to Airflow 2.5.0
  openverse_catalog/dags/common/operators/postgres_result.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  pytest.ini
  requirements_prod.txt
  tests/dags/common/operators/test_postgres_result.py
  tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#962 Update the deployment docs to showcase the bump version command
  DEPLOYMENT.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#961 Fix rotate_db_snapshot ARN template
  openverse_catalog/dags/maintenance/rotate_db_snapshots.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#945 Set `filesize` and `duration` overflowed values to `None`
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/media.py
  tests/dags/common/storage/test_audio.py
  tests/dags/common/storage/test_media.py
  tests/dags/providers/provider_api_scripts/test_stocksnap.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#745 iNaturalist in-SQL loading
  DAGs.md
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/create_schema.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/export_to_json.template.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/observers.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/photos.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/taxa.sql
  openverse_catalog/dags/providers/provider_csv_load_scripts/inaturalist/transformed_table.template.sql
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/providers/provider_api_scripts/resources/inaturalist/check_creator_metadata.py
  tests/dags/providers/provider_api_scripts/resources/inaturalist/exploring_catalog_of_life.py
  tests/dags/providers/provider_api_scripts/resources/inaturalist/pull_sample_records.py
  tests/dags/providers/provider_api_scripts/test_inaturalist.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#796 Add a Nappy provider DAG using ProviderDataIngester
  DAGs.md
  docker/local_postgres/0004_openledger_image_view.sql
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/common/popularity/sql.py
  openverse_catalog/dags/providers/provider_api_scripts/nappy.py
  openverse_catalog/dags/providers/provider_workflows.py
  tests/dags/providers/provider_api_scripts/resources/nappy/images.json
  tests/dags/providers/provider_api_scripts/resources/nappy/single_item.json
  tests/dags/providers/provider_api_scripts/test_nappy.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#948 Defer retrieval of GitHub API key to runtime
  openverse_catalog/dags/maintenance/check_silenced_dags.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code, 🔧 tech: airflow

#943 Temporarily increase Freesound delay & timeout
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  openverse_catalog/dags/providers/provider_workflows.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#944 Make Phylopic a dated-only DAG
  openverse_catalog/dags/providers/provider_api_scripts/phylopic.py
  tests/dags/providers/provider_api_scripts/test_phylopic.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#970 Increase Europeana reingestion timeout to 16 hours
  openverse_catalog/dags/providers/provider_reingestion_workflows.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#934 Finnish DAG: Dynamically generate timeslices depending on the amount of records
  openverse_catalog/dags/providers/provider_api_scripts/finnish_museums.py
  tests/dags/providers/provider_api_scripts/test_finnish_museums.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
