Repository WordPress/openverse-catalog, pull requests merged in 2023-02, with the labels that each got.

#960 Add task ID pattern to notification skip criteria
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/maintenance/check_silenced_dags.py
  tests/dags/common/test_slack.py
  tests/dags/maintenance/test_check_silenced_dags.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#971 Stripping the ImageCategory class of its "Enum" derivative, creating a new AudioCategory class, and removing 2 troublesome test directories
  openverse_catalog/dags/common/loader/provider_details.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/nypl.py
  openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
  tests/dags/common/storage/test_media.py
  tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-10T00_00_00+0000/1.log
  tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-10T00_00_00+0000/2.log
  tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-10T00_00_00+0000/3.log
  tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-20T00_00_00+0000/1.log
  tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-20T00_00_00+0000/2.log
  tests/dags/common/test_resources/logs/test_dag/test_task/2021-08-20T00_00_00+0000/3.log
  tests/dags/providers/provider_api_scripts/test_rawpixel.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#973 Discard audio file when preview 404s fetching filesize
  openverse_catalog/dags/providers/provider_api_scripts/freesound.py
  tests/dags/providers/provider_api_scripts/test_freesound.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#985 Upgrade to Airflow 2.5.1, remove old warnings
  pytest.ini
  requirements_prod.txt
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#990 Remove unnecessary dev dependencies
  requirements_tooling.txt
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#974 Update Europeana endpoint
  DAGs.md
  openverse_catalog/dags/providers/provider_api_scripts/europeana.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#969 Add dayshift to tsv filenames for reingestion workflows
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/providers/factory_utils.py
  openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py
  openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/common/storage/test_media.py
  tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
  tests/dags/providers/test_factory_utils.py
  tests/dags/providers/test_provider_dag_factory.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#994 Add an "Airflow Alert" issue template
  .github/ISSUE_TEMPLATE/airflow_alert.md
Labels: 🟩 priority: low, 📄 aspect: text, 🧰 goal: internal improvement

#1010 Remove API & Frontend repos from PR reminder check
  openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1001 Replaced `execution_date` with `logical_date`
  openverse_catalog/dags/common/slack.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/common/test_slack.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#995 Update Flickr to use new time delineated ingester class
  openverse_catalog/dags/providers/provider_api_scripts/finnish_museums.py
  openverse_catalog/dags/providers/provider_api_scripts/flickr.py
  openverse_catalog/dags/providers/provider_api_scripts/time_delineated_provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/resources/provider_data_ingester/mock_provider_data_ingester.py
  tests/dags/providers/provider_api_scripts/test_finnish_museums.py
  tests/dags/providers/provider_api_scripts/test_flickr.py
  tests/dags/providers/provider_api_scripts/test_time_delineated_provider_data_ingester.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1006 Preserve trailing slashes for WordPress URLs
  openverse_catalog/dags/common/storage/audio.py
  openverse_catalog/dags/common/storage/columns.py
  openverse_catalog/dags/common/storage/image.py
  openverse_catalog/dags/common/storage/media.py
  openverse_catalog/dags/providers/provider_api_scripts/wordpress.py
  tests/dags/common/storage/test_audio.py
  tests/dags/common/storage/test_columns.py
  tests/dags/common/storage/test_image.py
  tests/dags/common/storage/test_media.py
  tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1009 Ensure uniqueness of load table names
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/providers/provider_dag_factory.py
  tests/dags/common/loader/test_sql.py
Labels: bug, 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#717 Terminate PG query when task is killed via Airflow
  openverse_catalog/dags/common/loader/loader.py
  openverse_catalog/dags/common/loader/sql.py
  openverse_catalog/dags/common/popularity/sql.py
  openverse_catalog/dags/common/sql.py
  openverse_catalog/dags/data_refresh/dag_factory.py
  openverse_catalog/dags/data_refresh/data_refresh_types.py
  openverse_catalog/dags/data_refresh/refresh_popularity_metrics_task_factory.py
  openverse_catalog/dags/data_refresh/refresh_view_data_task_factory.py
  openverse_catalog/dags/database/image_expiration_workflow.py
  openverse_catalog/dags/database/report_pending_reported_media.py
  openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
  pytest.ini
  tests/dags/common/conftest.py
  tests/dags/common/loader/test_loader.py
  tests/dags/common/loader/test_sql.py
  tests/dags/common/popularity/test_sql.py
  tests/dags/common/test_sql.py
  tests/dags/providers/provider_api_scripts/test_inaturalist.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1021 Speed up some tests
  tests/dags/common/loader/test_sql.py
  tests/dags/common/test_requester.py
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1016 Update `Dockerfile`s with small improvements
  docker/airflow/Dockerfile
  docker/local_postgres/Dockerfile
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code
